// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ro'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​e​l​l​o​ ​W​o​r​l​d​!
	 */
	HI: string
	/**
	 * T​h​i​s​ ​i​s​ ​a​ ​t​e​s​t
	 */
	test: string
}

export type TranslationFunctions = {
	/**
	 * Hello World!
	 */
	HI: () => LocalizedString
	/**
	 * This is a test
	 */
	test: () => LocalizedString
}

export type Formatters = {}
